### ISSUE TITLE
New Allocation for DCSO

### ISSUE THREAD

**Issue by andurin** [sidallocation/sidallocation.org#13]
### What organization is requesting an allocation?

DCSO Deutsche Cyber-Sicherheitsorganisation GmbH

### How many sids are required?

10000

### Please provide reference links

https://medium.com/@DCSO_CyTec
https://github.com/DCSO/suricata-rules

### IDS Engine

- [ ] Snort
- [X] Suricata

**Comment by travisbgreen** [comment]
@andurin would this range be acceptable?
`3200000-3299999`

**Comment by andurin** [comment]
I would be fine with it - atm we are in the private range and anything else is better. Thanks in advance

04.01.2023 19:01:51 Travis Green ***@***.***>:

**Comment by travisbgreen** [comment]
Great! Changes have been made for `3200000-3299999`, closing issue.
