### ISSUE TITLE
New Allocation for Corelight

### ISSUE THREAD

**Issue by vstoffer** [sidallocation/sidallocation.org#15]
### Contact Details

vince@corelight.com

### What organization is requesting an allocation?

Corelight

### How many sids are required?

100,000

### Please provide reference links

We have started to create a number of our own Suricata rules.  We open-source many of them, here is an example:

https://github.com/corelight/C2-detection-manjusaka
https://corelight.com/blog/detecting-manjusaka-c2-framework

We've already started using the range 3000000, so we would request the range 3000000-3099999 since that appears available.  We can also start with a smaller range if that's preferable, please start with 3000000 and build up.

### IDS Engine

- [ ] Snort
- [X] Suricata

**Comment by jasonish** [comment]
This look fine to me.  If no one disagrees I'll make the change in 24 hours.

**Comment by travisbgreen** [comment]
changes made in PR: https://github.com/sidallocation/sidallocation.org/pull/17
