### ISSUE TITLE
New Allocation for ET Open offering - Stalkerware indicators of compromise

### ISSUE THREAD

**Issue by rgonzale6** [sidallocation/sidallocation.org#18]
### Contact Details

rgonzalez@proofpoint.com

### What organization is requesting an allocation?

Proofpoint

### How many sids are required?

10,000

### Please provide reference links

integration into ET Open offering from: https://github.com/AssoEchap/stalkerware-indicators/blob/master/ioc.yaml

### IDS Engine

- [X] Snort
- [X] Suricata

**Comment by zoomequipd** [comment]
This might be a good opportunity to carve out the following range for ET
2620000-2799999

This is right below the existing ETPRO rule, and just above the range for TGI HUNT.

The only issue there is this puts a hard limit on @travisbgreen with allocating another range, or moving TGI HUNT.

**Comment by jasonish** [comment]
2620000-2629999 is already assigned to 3COREsec.  I see we have an ordering issue on the page.

**Comment by zoomequipd** [comment]
Good Call. 

2700000 - 2799999 ?? 

This leaves the 263XXXX-2699999 open and provides ET a set that is continuous to what they already have allocated.

**Comment by travisbgreen** [comment]
:+1: that sounds good here

I'll plan on moving TGI HUNT and 3CORESec LATERAL to clear the way to a contiguous 2-3000000. Should be a straightforward move for TGI HUNT, but I'll have to check a couple of things for 3CORESec.

**Comment by travisbgreen** [comment]
Also, I did [a quick update](https://github.com/sidallocation/sidallocation.org/commit/3163ed4dd18e42f896aa71ee11a6f4d6e688afb7) to index.md to fix the order.

**Comment by zoomequipd** [comment]
Ok, for now, lets go ahead and do 2700000 - 2799999 so @rgonzale6 has what he needs for the STALKERWARE IOCs. 
Once TGI HUNT and 3CORESec LATERAL are moved, we can make additional updates.
