### ISSUE TITLE
New Allocation for ExtraHop

### ISSUE THREAD

**Issue by Dan-at-Extrahop** [sidallocation/sidallocation.org#21]
### Contact Details

@Dan-at-Extrahop

### What organization is requesting an allocation?

ExtraHop Networks

### How many sids are required?

100,000

### Please provide reference links

https://www.extrahop.com/solutions/security/ids/

We're beginning to create first-party Suricata rules. We would like to request to reserve the range 4000000-4099999.

### IDS Engine

- [ ] Snort
- [X] Suricata

**Comment by travisbgreen** [comment]
Looks good @Dan-at-Extrahop, I will add that in about 15 hours (to give others a chance to comment).

**Comment by travisbgreen** [comment]
Updated `index.md` with the new range. @Dan-at-Extrahop please review https://sidallocation.org and let me know if you see any errors

**Comment by Dan-at-Extrahop** [comment]
Thanks @travisbgreen, all looks good 👍
