### ISSUE TITLE
New Allocation for [Antiphishing] 

### ISSUE THREAD

**Issue by julioliraup** [sidallocation/sidallocation.org#26]
### Contact Details

jul10l1r4@disroot.org

### What organization is requesting an allocation?

N/A

### How many sids are required?

100000

### Please provide reference links

Project page: https://github.com/julioliraup/Antiphishing

### IDS Engine

- [ ] Snort
- [X] Suricata

### Download Links

https://raw.githubusercontent.com/julioliraup/Antiphishing/main/antiphishing.rules

**Comment by zoomequipd** [comment]
@julioliraup  just a side note, would you be willing to provide the same data using [Suricata Datasets](https://docs.suricata.io/en/latest/rules/datasets.html) as well?  This would allow you to have 3 rules which reference the entire list of domains.

**Comment by julioliraup** [comment]
I thought it was a great idea! I will implement it as soon as possible. If you want too, feel free!

**Comment by julioliraup** [comment]
@zoomequipd But I think that to be clear what information about each threat, I think it's better without the dataset. When in doubt, I think it's worth keeping both ways.

**Comment by zoomequipd** [comment]
It would only apply to the TLS and DNS rules that you produce and if metadata is enable on the alert eve type, it will contain the protocol information, thus providing the alert with the domain that triggered the rule from the dataset.   We can take this convo over to your repo, there are some other items with the rule format that could be addressed too.

**Comment by julioliraup** [comment]
PR merged of project
