### ISSUE TITLE
New Allocation for Emerging Threats

### ISSUE THREAD

**Issue by Dmkaz** [sidallocation/sidallocation.org#31]
### Contact Details

dkaczmark@proofpoint.com

### What organization is requesting an allocation?

Emerging Threats

### How many sids are required?

100,000,000

### Please provide reference links

Requesting the following SID range: `100,000,000 - 199,999,999`

This will be for future use as a collapsed range for both ETOPEN and ETPRO rules. 

### IDS Engine

- [X] Snort
- [X] Suricata

**Comment by travisbgreen** [comment]
Looks good here Dan. I'm going to let it bake for 24-36h to give others a chance to comment and then add it to the index.

**Comment by jasonish** [comment]
Looks OK to me.

**Comment by travisbgreen** [comment]
@Dmkaz @jasonish do you think there's any risk of confusion with the local range?

**Comment by jasonish** [comment]
No, we also have PT at 10,000,000.  Either way these large numbers are kinda hard to look at  :)
